# Generated by Django 5.2 on 2025-04-24 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoModel',
            fields=[
                ('repo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'repo',
                'verbose_name_plural': 'repos',
                'db_table': 'tb_repo',
            },
        ),
    ]
