# Generated by Django 5.2 on 2025-04-29 19:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoForksModel',
            fields=[
                ('repo_fork_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.repomodel')),
            ],
            options={
                'verbose_name': 'repo_fork',
                'verbose_name_plural': 'repo_forks',
                'db_table': 'tb_repo_fork',
            },
        ),
        migrations.CreateModel(
            name='RepoIssueModel',
            fields=[
                ('repo_issue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_title', models.CharField(blank=True, max_length=250, null=True)),
                ('issue_description', models.CharField(blank=True, max_length=250, null=True)),
                ('issue_status', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('repo_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.repomodel')),
            ],
            options={
                'verbose_name': 'repo_issue',
                'verbose_name_plural': 'repo_issues',
                'db_table': 'tb_repo_issue',
            },
        ),
        migrations.CreateModel(
            name='RepoStarsModel',
            fields=[
                ('repo_stars_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.repomodel')),
            ],
            options={
                'verbose_name': 'repo_star',
                'verbose_name_plural': 'repo_stars',
                'db_table': 'tb_repo_star',
            },
        ),
    ]
