# Generated by Django 5.2 on 2025-05-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repoforksmodel_repoissuemodel_repostarsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoobjectmodel',
            name='repo_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
