# Generated by Django 5.2 on 2025-04-26 13:45

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_repomodel_repo_description_repomodel_repo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoObjectModel',
            fields=[
                ('repo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to=core.models.user_directory_path)),
            ],
            options={
                'verbose_name': 'repo_object',
                'verbose_name_plural': 'repo_objects',
                'db_table': 'tb_repo_object',
            },
        ),
        migrations.AddField(
            model_name='repomodel',
            name='repo_object_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.repoobjectmodel'),
        ),
    ]
