# Generated by Django 5.2 on 2025-04-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_repoobjectmodel_repomodel_repo_object_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repomodel',
            name='repo_object_link',
        ),
        migrations.AddField(
            model_name='repoobjectmodel',
            name='repo_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.repomodel'),
        ),
    ]
