# Generated by Django 5.2 on 2025-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_repoobjectmodel_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repoobjectmodel',
            name='upload',
        ),
        migrations.AddField(
            model_name='repoobjectmodel',
            name='upload_hash',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
