# Generated by Django 5.2 on 2025-05-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_repoobjectmodel_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repoobjectmodel',
            name='repo_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='core.repomodel'),
        ),
    ]
