# Generated by Django 5.2 on 2025-05-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_repoobjectmodel_repo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoobjectmodel',
            name='branch',
            field=models.CharField(default='main', max_length=100),
        ),
    ]
