# Generated by Django 5.2 on 2025-05-09 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_repoobjectmodel_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='repoobjectmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
